# YML version
version: '3'

# Define all the services our book application needs
services:
  order-service:  # node application
    restart: always # automatically restart if the app fails
    image: yanivbhamo/burgernaut-order-service:1.0.0
    environment: # environment variables
      - PORT=3000
      - MONGO_HOST=mongo # this should be the same as the name of the DB service below
      - SLEEP_TIME=20000
      - MEMPHIS_USERNAME=fastmart
      - MEMPHIS_TOKEN=memphis
    ports: 
      - '3000:3000' # map the ports as <host-port>:<container-port . The container-port should be the same as the PORT defined in environment.
  
  restaurant-service:  # node application
    restart: always # automatically restart if the app fails
    image: yanivbhamo/burgernaut-restaurant-service:1.0.0
    environment: # environment variables
      - MEMPHIS_USERNAME=fastmart
      - MEMPHIS_TOKEN=memphis
      - MONGO_HOST=mongo # this should be the same as the name of the DB service below
      - SLEEP_TIME=20000
  
  email-service:  # node application
    restart: always # automatically restart if the app fails
    image: yanivbhamo/burgernaut-email-service:1.0.0
    environment: # environment variables
      - MEMPHIS_USERNAME=fastmart
      - MEMPHIS_TOKEN=memphis
      - EMAIL_ID=nscidonotreply@gmail.com # Enter email of service account
      - EMAIL_PWD=jzwaonluilpuqntl # Enter password of service account
      - EMAIL_SERVICE=gmail # Enter email service 
      - SLEEP_TIME=20000